name: Test

on: 
  pull_request:
    branches: [ "main" ]

job:
  test:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      
      - name: Go Version
        run: go version

      - name: Go Test
        run: go test ./ -v