name: Test

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Go Version
        run: go version

      - name: Go Vet
        run: go vet ./

      - name: Go Test
        run: go test ./ -v